### ISSUE TITLE
Issue for Diyor

### ISSUE THREAD

**Issue by SarvarbekUsmonov** [SarvarbekUsmonov/ista131project#8]

**Comment by 21diyor** [comment]
<img width="1370" alt="Screenshot 2023-12-04 at 8 44 43 AM" src="https://github.com/SarvarbekUsmonov/ista131project/assets/146765956/22fce2dd-5b06-4427-993c-59bdbb58744d">
<img width="1252" alt="Screenshot 2023-12-04 at 8 43 53 AM" src="https://github.com/SarvarbekUsmonov/ista131project/assets/146765956/b7445761-e6aa-4692-b8a7-245d5d0a7404">
